### ISSUE TITLE
Blank Marlin mode screen and steady tone when going back to touch screen

### ISSUE THREAD

**Issue by bakaneko718** [bigtreetech/BTT-TFT35-E3-V3.0#11]
i have currently everything finally connected. if i go to marlin mode it gives me a blank screen. the screen is lit up but that is all. i have banner text uncommented, but the banner doesn't show up. i am using this with the skr e3 mini 1.2.

**Comment by bakaufman** [comment]
I have something similar. I am using GTR with TFT35-E3-v3.0. Touch screen works fine, Marlin mode (2.0.4.4) does as described above. Tracing the EXP1 and EXP2 layouts suggests that they should match and don't need to be flipped. I have #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER in configuration.h. Any suggestions or should we just replace the screen?

**Comment by bakaneko718** [comment]
i have #define REPRAP_DISCOUNST_FULL_GRAPHIC_SMART_CONTROLLER set also. since its the ender 3 i followed the lay out in the instructions and have it in exp3 on the screen.

**Comment by bakaufman** [comment]
I am worried that the TFT35-V3.0 firmware doesn't work correctly with the E3 version of the board. Too bad BIGTREETECH NEVER READS THEIR GITHUB PAGE.

**Comment by bakaneko718** [comment]
i've seen people say they've worked with them, and have sent new screens. i've reached out to them about another issue that i fixed, but they haven't responded to that either.

**Comment by mduquette74** [comment]
I've tried both classic and unified on TFT35 E3 v2 and V3.  Both have the issues on both screens, and now the V3 is completely blank and will not boot. I'm completely stuck!

**Comment by oldman4U** [comment]
Hello.

Any news regarding the reported issue?

Using a single cable for Marlin Mode which connects the TFT (using EXP3) and the mainboard, the CR-10 display has to be defined in the Marlin FW of the mainboard.

**Comment by oldman4U** [comment]
Hello @bakaneko718.

Could you please close this ticket in case the problem has been solved in the meantime.

Thank you

**Comment by oldman4U** [comment]
Has someone of you ever tried
#define CR10_STOCKDISPLAY instead of
#define REPRAP_DISCOUNST_FULL_GRAPHIC_SMART_CONTROLLER?

Works fine on my machine.

**Comment by oldman4U** [comment]
@bigtreetech 

Please close this unused ticket.

Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by bakaneko718** [comment]
sorry i had not commented on this issue. nothing worked. i have been just using the classic side. i have tried commenting out reprap and leaving cr10 display. along with other things. i dont use the touch screen side anymore only the emulator side.

**Comment by oldman4U** [comment]
Thank you for closing this ticket. What you describe is exactly the opposite of the headline of the ticket. But I am happy to hear that the Marlin mode works now.

What is the problem with the touchscreen? No printer attached?

**Comment by bakaneko718** [comment]
sorry it's be a while and life caught up. i scrolled through and started recalling better. the original screen was bad. i was sent a new one from amazon. everything was reconnected and the display works. i am able to control the printer, but i cannot print in tft mode. it gives a message and i have to reset everything. the error message is along the lines of echo unknown error m33 then the file name. however, it has been a while and i dont have the files i used to make the firmware and had upgraded my computer and cant get vsc to compile anymore. so i have a slew of issues i'd need to work through that i dont have the time to do now.
