### ISSUE TITLE
NEW - TFT35 E3 V3.0 and SKR Mini E3 V 1.2

### ISSUE THREAD

**Issue by midmadn** [bigtreetech/BTT-TFT35-E3-V3.0#14]
I had a problem at first with the TFT35. Just when I was about to package it back up I hooked it up uninstalled and it started working. Even though it felt perfect - maybe the reset button I printed was putting a slight amount of pressure on the button. I have it all re-installed and it's working great now.
Thank You for wonderfull products.

Jack

**Comment by n3rdz** [comment]
same here, purchased 20.04.2020 on amazon

Update: i found that if i unscrew the TFT, the bug is gone, so i think it might be a grounding problem

**Comment by midmadn** [comment]
Working great now.
