### ISSUE TITLE
Weel steps.

### ISSUE THREAD

**Issue by Heartlander81** [bigtreetech/BTT-TFT35-E3-V3.0#17]
What must i write in Marlin for the weel steps at the encoder? I mean "encoder pulses per step" and "encoder steps per menu item"
Must i reverse the encoder direction, menu direction ore Both option?

Thanks.

**Comment by oldman4U** [comment]
Hi.

I never changed such a setting and all my encoders work fine. What is the problem or what would you like to achieve?

**Comment by Heartlander81** [comment]
Hi. I have changed my Marlin Firmware and now is all good.

I think the problem ist in my config. Then i have the original tvt from
anycubic and the tft 35. I want run both tft at same time. But under Marlin
2.0 is the tft 35 my favorit and i have disconnected my anycubic tft.
Thanks for your requests.
I wish u a nice time.

Sven Baum

oldman4U <notifications@github.com> schrieb am Fr., 29. Mai 2020, 12:46:

**Comment by oldman4U** [comment]
Sounds great.

Could you please close this ticket in case you think it is not needed any more.

Thank you
