### ISSUE TITLE
Changing print settings during print in Unified Menu freezes system

### ISSUE THREAD

**Issue by wheelyjoe** [bigtreetech/BTT-TFT35-E3-V3.0#21]
I have an SKR Mini E3 v1.2 and whenever I change a setting during print (ie fan %, flow rate, etc), then that value starts flickering and the print freezes when the next command should be sent.

**Comment by oldman4U** [comment]
Hi.

This issue has been solved ninth latest release of the TFT software yesterday. Do you know how to compile software?

**Comment by wheelyjoe** [comment]
I do! That's great!

**Comment by oldman4U** [comment]
👍 For me the issue is solved. Could you please close this ticket once it also works for you. Thank you

**Comment by wheelyjoe** [comment]
Yup, I'll have a go tonight and close it if all is well!

**Comment by oldman4U** [comment]
👍happy printing

**Comment by wheelyjoe** [comment]
Seems to have done the trick! - Closing
