### ISSUE TITLE
touch screen does not light up or work

### ISSUE THREAD

**Issue by wkrogers** [bigtreetech/BTT-TFT35-E3-V3.0#23]
I have an ender 3 pro.  I just upgraded the controller board to an SKR Mini E3 V2.0+TFT35 E3 V3.0.  When powering up can hear fan but no display.  Hook up original display and it works perfect.  Any suggestions

**Comment by oldman4U** [comment]
Hi. How have you connected the display. Maybe a picture could help.

**Comment by oldman4U** [comment]
Any news? Please let us know. Thank you

**Comment by oldman4U** [comment]
Could you please close this ticket in case you found the problem. 

Thank you

**Comment by oldman4U** [comment]
@bigtreetech 

Could you please close this ticket. Seems this user does not know how to do this.

Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by wkrogers** [comment]
how do i close?  Found cable that came with display bad.
________________________________

**Comment by oldman4U** [comment]
Using a web browser you have a Close button at the bottom of the ticket. On iOS you can drag the line right above the Comment up, wich opens a window like shown at attached screenshot. ![image](https://user-images.githubusercontent.com/54359396/95025769-6a16cf80-068c-11eb-98e3-e88912cb4019.png)

Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by wkrogers** [comment]
That is on a celll phone - I don't use a cell phone
________________________________

**Comment by oldman4U** [comment]
In the browser on PC you click Close or Comment and Close.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
