### ISSUE TITLE
TFT35 V3.0 Stuck in Boot Mode Selection

### ISSUE THREAD

**Issue by Power3DPrinting** [bigtreetech/BTT-TFT35-E3-V3.0#24]
Hi, I just bought a TFT35 V3.0 from bigtreetech and debating to return it before even mounting it because I have it plugged into EXP1 and EXP2 and I get a blank screen. If I plug in the TFT 5V,GND, TX, RX into AUX 1, I get a blank screen. It is only if I plug in both that I can get it to turn on and then it is stuck in mode selection asking if I want to be in marlin mode or touch mode. Touching the screen and the encoder both do not work, only the reset button works.

I am running a MKS_SGEN_L, it boots, I can connect with pronterface, as far as I can tell, the mainboard and marlin config are fine. REPRAP full graphic display is enabled in config.h.

Not really sure how to fix this. I saw some people talking about their metal case shorting it out but I don't have a metal case and it is sitting on a wooden table.

I appreciate any help! Thanks!

**Comment by oldman4U** [comment]
Hi. I would open a ticket in the general touchscreen repository. This is only for E3 TFT. 

PLEASE close the ticket here

Thank you
