### ISSUE TITLE
TFT unresponsive when mounted to chassis

### ISSUE THREAD

**Issue by SideQuestEngineer** [bigtreetech/BTT-TFT35-E3-V3.0#25]
The screen works fine until you screw it into the screen display using the 4 M2.5 screws. This is for and Ender 3 pro and this is the 2nd copy of the LCD that behaves identically. 

When you unmount the display from the frame, it works just fine.

Connected to SKR Mini e3 v2 via TFT and original cable.

I’m unable to compile Marlin so I’m using th supplied firmware for the mini e3 v2.0

**Comment by oldman4U** [comment]
Hi. This is a known issue which can be solved easily by insulating the tft and the metal frame using a bit of insulation tape. Could you please make a picture of the back of the tft how you got it from btt and upload it here. 

Thank you

**Comment by SideQuestEngineer** [comment]
![image](https://user-images.githubusercontent.com/6478437/89474906-7cd45d00-d74c-11ea-89e7-70f25e4aa1e2.jpeg)

That makes sense, but i don't see where it is touching the metal? It looks like the board only makes contact with the standoffs.

I will insulate around the outside of the board and remount.

**Comment by oldman4U** [comment]
Insulate also where the standoffs Touch the display with tape or a plastic
washer.

ventoetc <notifications@github.com> schrieb am Do. 6. Aug. 2020 um 01:51:

**Comment by oldman4U** [comment]
Hi. Hope everything works properly. Please do not forget to close this ticket 

Thank you

**Comment by SideQuestEngineer** [comment]
After insulating the front of the panel, the shorting issue has stopped.
