### ISSUE TITLE
Knob LED not working. Unknown Comand: "M105 R0 U255 B0 P255"

### ISSUE THREAD

**Issue by PigeonFX** [bigtreetech/BTT-TFT35-E3-V3.0#27]
Whenever I try and set the LED colour I get the error:

`Unknown Comand: "M105 R0 U255 B0 P255"`

Using Marlin 2.0.6 and the latest TFT35 Firmware from the BTT Github.

**Comment by oldman4U** [comment]
Hi. Could you please close this ticket. Seems you have found the right menu in the meantime. Thank you
