### ISSUE TITLE
LCD showing error message when I try to set LED color

### ISSUE THREAD

**Issue by RedCoder09** [bigtreetech/BTT-TFT35-E3-V3.0#29]
It displays an "unknown command" message and then does nothing.

**Comment by oldman4U** [comment]
This is to change an external LED. Please use the corresponding setting to change the color of the knob.

**Comment by RedCoder09** [comment]
> This is to change an external LED. Please use the corresponding setting to change the color of the knob.

What corresponding setting?

**Comment by RedCoder09** [comment]
Figured it out. Thanks!

**Comment by RedCoder09** [comment]
But what LED does the other setting set?

**Comment by oldman4U** [comment]
LED stripes connected to the mainboard via RGB or Neopixel connector.
Usually to illuminate the Nozzle area or the housing.

RedCoder09 <notifications@github.com> schrieb am Mo. 24. Aug. 2020 um 00:26:

**Comment by RedCoder09** [comment]
Thanks!

**Comment by oldman4U** [comment]
You are welcome
