### ISSUE TITLE
Continuous beep when switching back to the touch screen

### ISSUE THREAD

**Issue by 94Porsche968** [bigtreetech/BTT-TFT35-E3-V3.0#3]
Switching between the screens works fine but when switching back to the touch screen the machine beeps continuously.  The mainboard is an SKR E3 Dip-V1.1.  I've only been able to stop the beeping by powering down the machine.  The touch screen is running with BIGTREE_TFT35_V3.0.25.1.

UPDATE:  Side note... initially when starting the machine up the screen gives me an ABL warning and the BLTouch is unresponsive.  This last time I turned it on, after making no changes, got no message and the BLTouch would deploy and stow.  Switched screens and the beeping returned but this time with the ABL error -"Failed to enable Bed Leveling  echo: Bed Leveling  OFF  echo:Fade Height  OFF  ok" - hitting the "CONFIRM" button does not stop the beeping.

Wondering if the beeping is triggered by the error but does not stop when confirmed.

**Comment by hfog** [comment]
I have encountered exactly the same thing. I can silence the beep by turning off the speaker in the machine settings menus but that turns off all beeps on the device so it's not an ideal solution. 
I came here specifically to register this same issue so I'm glad I'm not the only one to hit it.

**Comment by critter42** [comment]
I am experiencing the same issue. It's quiet on boot-up, then I switch to Marlin Mode and it is fine also. I switch back to Touch Screen and it starts the tone. It will stop if I switch back to Marlin, but then start again when I go back to Touch Screen. I don't do ABL so I can't advise on the other issue

Update: The tone only seems to start if I TOUCH the BTT Icon. If I select it with the encoder wheel and button, it switches normally. However, as soon as I touch to switch to BTT, it starts the tone again and continues even when using the wheel and encoder. I did notice in the mode.c file there is an unused variable nowEncoder, but I couldn't see where that had any relevance.

Update 2: I should add I am connecting this to a BTT SKR 1.4 Turbo if that makes any difference

**Comment by oldman4U** [comment]
Hi @94Porsche968.

Seems this issue has been fixed for sometime now. So could you please close this ticket.

Thank you

**Comment by Next-victim** [comment]
Just dealt with something like this. My solution was to comment out PID_DEBUG with both PIDTEMP and PIDTEMP active. I had enabled PIDTEMPBED and the debug right before this started happening, no consistant beeping after commenting the debug out.

Board: SKR 1.4 turbo (24v setup)
Screen: BTT TFT43
Attached USB: Pi4 running current OctoPi
