### ISSUE TITLE
TFT35 Encoder knob sets speed no matter which screen you're on

### ISSUE THREAD

**Issue by leopshef** [bigtreetech/BTT-TFT35-E3-V3.0#31]
TFT35 Encoder knob sets speed no matter which screen you're on for example If you change your temperature using the encoder knob then the speed value is also changed.

**Comment by oldman4U** [comment]
Please see my answer in the TFT35 repository.

And please do not forget to close tickets you do not need anymore.

Thank you

**Comment by leopshef** [comment]
Thank you.

**Comment by oldman4U** [comment]
👍🏻

leopshef <notifications@github.com> schrieb am Di. 25. Aug. 2020 um 21:53:
