### ISSUE TITLE
Tft35 e3 v3 not turning on

### ISSUE THREAD

**Issue by kabone** [bigtreetech/BTT-TFT35-E3-V3.0#38]
I have a skr mini e3 2.0 and tft35 e3 v3. It was working good. After a reboot of my printer the screen is not turning on. I ordered a replacement that one also is not turning on. If i flip the tft pins it turns on with a white line across. If i remove the tft pins and plugin to ext1 it powers on and looks correctly. Anything i can do to overcome this?

**Comment by oldman4U** [comment]
What do you mean with remove the tft pins?

You have to connect the RS232 cable on the TFT and the mainboard and EXP on mainboard to EXP3 of TFT. But you wrote this has been working before so you know this....

**Comment by kabone** [comment]
> What do you mean with remove the tft pins?
> 
> You have to connect the RS232 cable on the TFT and the mainboard and EXP on mainboard to EXP3 of TFT. But you wrote this has been working before so you know this....
I mean remove the tft wire. It was working, but ive since ordered a replacement to see if it was in fact the tft35 it turned out its an issue with the skr mini e3 v2.0. Both lcds worked when i hooked up the new board. The new lcd and old lcd did not work with the old skr mini. Ill go ahead and marked this closed.

**Comment by oldman4U** [comment]
Problem is solved!!??

This would be great 

Thank you for closing the ticket 

Happy printing

**Comment by kabone** [comment]
Well I had ordered another one after giving up with it. The new one just now did the same... Same exact situation Has been working for a few months and just randomly stopped working, turned it off after a print to turn it back on to a blank screen.. If I remove the wires and plug into ext1 it lights up. So I know it's still working. IS there anything I can do? 

**EDIT
So I've been testing a bit more. This is not an issue with the TFT35 E3 V3. It's the SKR Mini E3 V2.0 causing the issue.**

**Comment by radek8** [comment]
If you still have a problem, send Marlin configuration files and connector wiring photos.
I'll see if anything comes to mind

**Comment by kabone** [comment]
> If you still have a problem, send Marlin configuration files and connector wiring photos.
> I'll see if anything comes to mind

I reached out to the facebook support and sent videos of all this. They issued me 2 new boards. Everything worked right away with the new board and tft35 e3 v3
