### ISSUE TITLE
No Sounds coming from Speaker on Display

### ISSUE THREAD

**Issue by aModernGirlMakes** [bigtreetech/BTT-TFT35-E3-V3.0#39]
Any tricks for being able to turn sound on? I have no sounds coming from touch display. 
I have a BTT SKR Mini E3 V2.0 and the BTT-TFT35-E3-V3.0 installed on my Ender 3 Pro

**Comment by oldman4U** [comment]
Hi

Have you checked if Sound is on under the screen settings of the TFT?

**Comment by aModernGirlMakes** [comment]
yes, I have toggled sound on and off on the touch screen. 
I believe I have the latest firmware for the TFT board
What needs to be uncommented in Marlin 2.0? 
What is another way to test the buzzer/speaker?

**Comment by oldman4U** [comment]
With sound on you should hear a click every time you press a button. If this is not the case the hardware is broken. I replaced one already with a spare buzzer I had hanging around.

**Comment by aModernGirlMakes** [comment]
I don't hear anything. I have the original screen buzzer from the Creality Ender 3 Pro. Is it as simple as using a soldering iron to get it off the old board and replace the ?defective? one?

**Comment by oldman4U** [comment]
Broken. 

Yes it is. I added a cable so I could move it a bit away from the front.

![image](https://user-images.githubusercontent.com/54359396/93723021-6b7bce80-fb9b-11ea-8865-1e8913f93219.jpeg)

**Comment by aModernGirlMakes** [comment]
Wondering if I should get a new display from BTT since the board came this way. I don't think I should have to break out the soldering iron to fix something that should have arrived in working order. 
Thanks for your quick response to my question. Keeps me from banging my head over and over.

**Comment by oldman4U** [comment]
I agree. Contact the dealer you bought it from.

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Thank you and hope you find a good solution for the buzzer.
