### ISSUE TITLE
Touch screen will only allow you to go one level down on the SD card

### ISSUE THREAD

**Issue by 94Porsche968** [bigtreetech/BTT-TFT35-E3-V3.0#4]
When working with an SD card connected to the printer itself, not the TFT screen, the touch screen will only allow you to go one level down.  In other words, I can't get to a folder with a folder from the touch screen.  I am able to navigate the whole SD card in Marlin mode.

**Comment by oldman4U** [comment]
Hi fast car.

What is the status of the reported issue?

Please let us know, thank you

**Comment by oldman4U** [comment]
👍🏻

94Porsche968 <notifications@github.com> schrieb am Mi. 23. Sep. 2020 um
13:16:
