### ISSUE TITLE
TFT35 won't turn on with SKR 1.4 (need to unplug and re-plug EXP3 to work)

### ISSUE THREAD

**Issue by skippy3111** [bigtreetech/BTT-TFT35-E3-V3.0#41]
My TFT35 won't turn on with my printer. I need to unplug the EXP ribbon cable and plug it back in, then it works fine (in either LCD or TFT mode) till I power off my printer again. 

Some notes: 
 - Printer is an Ender 3 pro with an SKR 1.4 Turbo. Running Marlin 2.0.x. 
 - I have the EXP1 port on the mainboard connected to EXP3 on the TFT35. 

Any suggestions on how I can get it to power on with the printer without having to unplug and plug it back in?

Thanks!

**Comment by oldman4U** [comment]
Where did you saw that EXP cabeling?

**Comment by Roughd1433** [comment]
It should both exp cables to the same ports in the board and tft. Then the tft wires from the screen to the board. You need to make sure you match the 5v pins on the cable to the correct one on each end as some cables have the wires swapped when they were made.

**Comment by oldman4U** [comment]
It is important to know how a user can connect the cables so wrong. In this case the number of cables and the connector is wrong and somewhere the user saw this as the right solution.

**Comment by oldman4U** [comment]
But maybe this is one of the typical "first issue ever", where the user was only able to open the ticket, but not to close it...

@skippy3111 What is the status of the reported issue?

**Comment by skippy3111** [comment]
Hi guys, sorry got busy yesterday and haven't had a chance to try the 2nd
cable as suggested, as well as the other suggestions.

FYI I power on with only the TFT cable plugged in, it works in TFT mode
without any issues. So I don't think it's the TFT wire issues mentioned?

Let me refine the the problem description... if I want to use it in LCD
mode I need to plug in the LCD (EXP) cable after boot. If it's plugged in
at boot, even TFT mode is a blank screen until the cable is unplugged.

I'll take some pictures of the my wiring later today

Thanks!

**Comment by oldman4U** [comment]
Again. Where do you get the cable information from?

**Comment by oldman4U** [comment]
Connecting the cables wrong can also destroy your hardware, mainboard and/or TFT.

**Comment by skippy3111** [comment]
Hi guys, was busy with work all day. Just got a chance to have a look now. 

> Where did you saw that EXP cabeling?

@oldman4U I was following [Teaching Tech's video on SKR 1.4 installation](https://youtu.be/-Gdk0wHg51w?t=975) and [his video on the TFT35](https://www.youtube.com/watch?v=l1Putn10_Ek&t=270s). 

> It should both exp cables to the same ports in the board and tft. Then the tft wires from the screen to the board. You need to make sure you match the 5v pins on the cable to the correct one on each end as some cables have the wires swapped when they were made.

@Roughd1433 Tried this setup (see below). I also traced the 5v line (white/black on the rainbow ribbon), the red line on the grey ribbon, and the wires on RS232 cable and compared it to the pin-outs for the SKR1.4 and the TFT35. Seems to be all okay. 
![image](https://user-images.githubusercontent.com/72326890/95140627-54adae00-073d-11eb-9b2e-b0083e100af1.png)

With this setup the screen would power up with the printer and work in TFT mode, but the LCD mode would not work. To make this cabling work in LCD mode, should I change anything in the firmware?

Here's some other combinations I tried: 
**Case 1** (SKR EXP1 to TFT EXP3) - the screen powers on with printer and works in LCD mode. 
![image](https://user-images.githubusercontent.com/72326890/95141281-b6224c80-073e-11eb-8608-d41de249ce7a.png)

**Case 2** (SKR TFT to TFT RS232) - the screen powers on with printer and works in TFT mode. 
![image](https://user-images.githubusercontent.com/72326890/95141422-2761ff80-073f-11eb-803d-eca9dad62e8c.png)

**Case 3** (SKR EXP1 to TFT EXP3 & SKR TFT to TFT RS232) - screen does not power on with printer. If I unplug either cable it will power on, and then when I re-plug the same cable it will continue to work in either mode as desired (until I power off the printer). 
![image](https://user-images.githubusercontent.com/72326890/95141051-33998d00-073e-11eb-8956-f26c4bbbc65e.png)



> Connecting the cables wrong can also destroy your hardware, mainboard and/or TFT.

so far no issues 😅🤞

Thanks for the help guys!

**Comment by oldman4U** [comment]
Hi. 

Checked the movies and our friend from down under explains it right. 

![image](https://user-images.githubusercontent.com/54359396/95262728-f3fd9e80-082c-11eb-8b76-c12a17a3ce36.png)

and
![image](https://user-images.githubusercontent.com/54359396/95262746-0081f700-082d-11eb-8614-c37cf0315b3b.png)

So connecting RS232 for touch screen support AND EXP1 and EXP2 of the mainboard and the TFT for Marlin simulation. 

In Matlin ONLY REPRAP DISCOUNT FULL GRAPHICS SMART CONTROLLER must be activated. CR10 has to be deactivated by adding // in front. 

Let us know

**Comment by skippy3111** [comment]
> So connecting RS232 for touch screen support AND EXP1 and EXP2 of the mainboard and the TFT for Marlin simulation.
> 
> In Matlin ONLY REPRAP DISCOUNT FULL GRAPHICS SMART CONTROLLER must be activated. CR10 has to be deactivated by adding // in front.

@oldman4U ok so the screen powers on with the printer now. Works fine in TFT mode. In LCD mode, the knob's push button registers, however turning it doesn't do anything. 

FYI Here's the configuration files that I compiled with [Marlin-bugfix-2.0.x.zip](https://github.com/bigtreetech/BTT-TFT35-E3-V3.0/files/5338146/Marlin-bugfix-2.0.x.zip)


I didn't have a lot of time to dubug a lot today though. I'll give it another shot tomorrow evening. 

I'll start with compiling a new firmware file with a fresh set of Marlin configuration files with only the instructions you noted above, and will go from there. 

Will keep you posted. Thanks!

**Comment by oldman4U** [comment]
What do you mean with turning doesn’t do anything?

skippy3111 <notifications@github.com> schrieb am Mi. 7. Okt. 2020 um 05:47:

**Comment by skippy3111** [comment]
I can't scroll through the menus with the wheel. I can click once to enter
the menu screen, and click again to go back to the info screen, but can't
switch to any other menu option.

**Comment by skippy3111** [comment]
(been swamped with work, will try to make some time tomorrow)

**Comment by oldman4U** [comment]
When you are in the mode selection area, can you switch between the two modes using the knob?

**Comment by skippy3111** [comment]
> When you are in the mode selection area, can you switch between the two modes using the knob?

nope. no response from turning the knob.

**Comment by oldman4U** [comment]
Looks like a hardware issue to me. Had a broken encoder too. Live without Marlin or replace it.

**Comment by skippy3111** [comment]
Yeah I was afraid of that. I wonder if I damaged something when unplugging
and replugging the cables.

Will try to revert back to the previous firmware with the cr10 option
enabled.

Too darn busy with Thanksgiving though.

**Comment by skippy3111** [comment]
Success! Had a bad cable and it worked when I switched it out. 

So to recap, solution is to enable:
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

then disable:
//#define CR10_STOCKDISPLAY

and connect EXP1 to EXP1, EXP2 to EXP2. 

Thanks for the support @oldman4U and @Roughd1433!

**Comment by oldman4U** [comment]
And finally you found the reason for the problem!

👍🏻

Happy printing
