### ISSUE TITLE
Touchscreen doesn’t respond and screen is NOT touching the frame where it’s mounted in.

### ISSUE THREAD

**Issue by jlogin2002** [bigtreetech/BTT-TFT35-E3-V3.0#43]
Touchscreen doesn’t respond and screen is not touching the frame where it’s mounted in.

First time I swich on, system shows me a calibration screen but I could not do nothing at all. I powered off, powered on and touchscreen modo dos not work but emulation .

All ribon cables are ok, marlin configuration is ok I can operate my printer in emulation mode.

I look forward to hearing from  your news soon

Thank you

**Comment by oldman4U** [comment]
Hi.

This is a brand new TFT or has it been working before?
Which mainboard?
What exactly is connected on which connector of the TFT?
Which firmware and have you updated the firmware already?
Does it work with only the RS232 cable connected?

**Comment by jlogin2002** [comment]
I close the issue into this branch because I have opened in the right place. I respond into the proper thread
