### ISSUE TITLE
No display while connected to either port 

### ISSUE THREAD

**Issue by dustybandago** [bigtreetech/BTT-TFT35-E3-V3.0#44]
I went to turn on my printer and everything turns on except for the display. when I connect the ribbon cable to the display I can get a beep when I press down on the button but that it. nothing happens with the serial port at all. I also tried the reset button with no results. I also tried to reflash it but nothing happpened still.

**Comment by oldman4U** [comment]
Hi. 

Which mainboard are you using?

**Comment by dustybandago** [comment]
skr mini e3 v2.0

**Comment by oldman4U** [comment]
So nothing even you have only serial cable connected?

Can you send pictures of front and back of the screen while connected and turned on.

**Comment by dustybandago** [comment]
I connected the OEM display from my ender 3 and it works so I know its not the main board

**Comment by dustybandago** [comment]
![20201023_104455](https://user-images.githubusercontent.com/73313537/97018416-21309900-151d-11eb-8ab4-083ef63a9ca5.jpg)
![20201023_104442](https://user-images.githubusercontent.com/73313537/97018420-21c92f80-151d-11eb-8f21-83aef3619ba5.jpg)

**Comment by oldman4U** [comment]
The display gets power....

Can you hear a sound when you touch the screen while it is turned on.

Looks like a broken backlight to me.

This is how the bottom of a working screen looks like.  

![image](https://user-images.githubusercontent.com/54359396/97034284-f79b6000-1564-11eb-8fd2-9f1503cb9a4b.jpeg)

**Comment by dustybandago** [comment]
there is no sound when I touch the screen. I don't even get the beeps to swap over to marlin mode. the backlight isn't coming on either. 
I think I'm just going to toss it up as a loss and take it as an opportunity to get the TFT 70.

**Comment by oldman4U** [comment]
You should contact your dealer if it is new. But this unit seems to be broken 😔. Sorry

**Comment by dustybandago** [comment]
it ok, thank you for your help

**Comment by oldman4U** [comment]
You could do the ultimate test by cutting a USB cable and connecting the red and black strip to 5V and GND to the serial port of the TFT. It has to start normally.

**Comment by dustybandago** [comment]
I was able to get a replacement but I might try that too.
