### ISSUE TITLE
Screen tells me no printer attached with SKR Mini E3 V2.0

### ISSUE THREAD

**Issue by rasimif** [bigtreetech/BTT-TFT35-E3-V3.0#45]
Screen is connected to said board at 115200 baudrate, there's nothing else connected to the board except the screen and power supply. Any ideas what I'm doing wrong?

**Comment by oldman4U** [comment]
Which baud rate do you have defined in Marlin of the SKR?

Attach pictures showing the connection from SKR to TFT.

Is this a new setup or has this been working before?

Any spare parts you could use to try different setup?

The screen shows the touchscreen UI as soon as it gets power.

**Comment by rasimif** [comment]
Thanks for your swift reply. 
The baudrate is defined as 115200, this is meant to be an upgrade to an old printer, changing board + screen. 
Old board and screen are from an Anet A6 running Marlin. The reset button on the screen works and resets screen + board.
Simplify 3D gets a connection to the board over USB.
EDIT: The Screen also works in Marlin mode, just not in touch mode.
![DSC_0393](https://user-images.githubusercontent.com/73956642/98143988-1a653700-1eca-11eb-8d50-18fc1b9180a1.JPG)
![DSC_0392](https://user-images.githubusercontent.com/73956642/98144010-1f29eb00-1eca-11eb-8015-6baf35a0b4ad.JPG)

**Comment by oldman4U** [comment]
Cable wrong....

Would be nice to let me know.
