### ISSUE TITLE
Unknown Command M503 S0 Error

### ISSUE THREAD

**Issue by agenttatdaddy** [bigtreetech/BTT-TFT35-E3-V3.0#46]
I got this screen a few weeks ago. Since day one I get an error pop-up that says "echo; Unbknown Command; M503 S0" The gcode M503 has something to do with EEPROM memory. I flashed the newest firmware and the problem still exists. I found no info on this issue at all. However, I did come across a site that had a similar issue and recommended creating a file called "eeprom.dat" and placing it on the root of the SD card with no luck as well.. But that was for enabling the EEPROM M500, M501, M502,  gcodes, as well as disable M503. In marlin, I disabled that function, but I do not think it applies to the TFT screen. I do not see any issues with prints, and I do not see any issues with the printer that I am aware of, and while it doesn't seem to mess anything up, it is quite annoying to have an error message pop up every time I mess with any settings in the menu. Any help would be greatly appreciated.

**Comment by oldman4U** [comment]
Unlikely a hardware issue so I would close this ticket and ask the same in the firmware repository.
