### ISSUE TITLE
Where is the firmware?

### ISSUE THREAD

**Issue by artiface** [bigtreetech/BTT-TFT35-E3-V3.0#49]
I do not see any firmware files for this device in this github?

**Comment by oldman4U** [comment]
There is a firmware repository.

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Have you found the firmware?

Please let me know

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by doug-scott** [comment]
Where is this firmware located?  Simply saying "There is a firmware repository" is only stating the obvious.  I know there must be a firmware repository, but, I do not know where.

**Comment by radek8** [comment]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

**Comment by oldman4U** [comment]
artifice Have you found the firmware?

**Comment by oldman4U** [comment]
@doug-scott This is the reason why it is so hard to help. There are many "I open a ticket for the first time" users, which are not able or willing to make two clicks more, but it is easier for them to open the ticket and never close it after that. The alternative would be to give no answer at all, which would end up like this: https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/issues

@artiface Respond or close the ticket

**Comment by artiface** [comment]
thanks to radek8 for actually posting the link which was helpful, unlike the other commenter just telling me to close the ticket over and over.
