### ISSUE TITLE
Unable to use the touch screen when a print job is initiated on Marlin side

### ISSUE THREAD

**Issue by 94Porsche968** [bigtreetech/BTT-TFT35-E3-V3.0#5]
When I initiate print jobs on the Marlin side, I am unable to go back and use the touch screen.  The touch screen states there is no printer connected.  The touch screen showed a printer connected prior to changing over to Marlin mode to start the print job.  The job WILL print.  I just have no control from the touch screen.

**Comment by oldman4U** [comment]
Is this still an issue?

Please help us to keep this repository maintainable by closing unneeded tickets. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
