### ISSUE TITLE
Hi. Which sd card and which firmware. Has the screen working before or is it a new installation?

### ISSUE THREAD

**Issue by chadumisprime** [bigtreetech/BTT-TFT35-E3-V3.0#50]
Hi. Which sd card and which firmware. Has the screen working before or is it a new installation?

_Originally posted by @oldman4U in https://github.com/bigtreetech/BTT-TFT35-E3-V3.0/issues/33#issuecomment-687174990_

I’m having this same issue

**Comment by oldman4U** [comment]
Which issue?

More information could help. Like firmware version, pictures of the cabling, problem description...

**Comment by chadumisprime** [comment]
I have attached a few photos and a video of the issue. I’ve updated to marlin 2.0.7  I also have a Bltouch connected. 
When I turn the ender 3 pro on, the screen comes on the shuts off within 10 seconds. This also happens when I plug the original printer screen in. 
![33DEBA40-48DE-48DB-B923-3DA7B618422F](https://user-images.githubusercontent.com/74875037/99917460-4acc1400-2cc5-11eb-9db3-7f8b9b0ac457.jpeg)
![20384C08-6EB4-49EE-922F-D5C424662B70](https://user-images.githubusercontent.com/74875037/99917464-50295e80-2cc5-11eb-89c0-db38603b68f4.jpeg)

**Comment by oldman4U** [comment]
Sounds like the tFT does not get enough power.

You can verify if the TFT works by cutting a USB cable and connect the red wire to 5V and the black wire to GND of the Power connector. Doing so the TFT should power up and stay like this. Disconnect all other cables from the TFT for this.

**Comment by oldman4U** [comment]
Any news?

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by radek8** [comment]
According to the photo, I assume that the problem was in the incorrectly connected connector from BL-Touch?
It is so?
