### ISSUE TITLE
SKR E2 V2 and bigtree tech e3 v3 tft screen wifi not working. esp 8266

### ISSUE THREAD

**Issue by Talha909** [bigtreetech/BTT-TFT35-E3-V3.0#51]
I had SKR E2 V2 and bigtree tech e3 v3 tft screen. I also have ESP8266. I configure the ESP8266 and installed the esp into my tft screen. I connect the tft with the wifi. But i cant able to move my printer. Do i have to make any change in marlin.

**Comment by oldman4U** [comment]
Hi

Please send a picture which shows the module and the TFT.

**Comment by Talha909** [comment]
![ESP01](https://user-images.githubusercontent.com/29024390/100832963-bd3db080-348a-11eb-8699-a9b9f8b1a8c9.JPG)
![tft](https://user-images.githubusercontent.com/29024390/100832976-c169ce00-348a-11eb-8b07-4503e440fa04.JPG)
 I did not change the any thing in Marlin. I put the esp 8266 on the back of tft. I got the display of esp8266 on my screen. And lot errors comes on the lcd screen.  But i cant able to control the printer from the lcd

**Comment by oldman4U** [comment]
Please send a picture of your tft and esp device. I did not change anything in Marlin.

**Comment by oldman4U** [comment]
Any news?

**Comment by oldman4U** [comment]
Does it work?

**Comment by Talha909** [comment]
I simply purchased the new esp01s and its works good. I did not whats the problem with the old one. bout are same.

**Comment by oldman4U** [comment]
👍🏻

Talha909 <notifications@github.com> schrieb am Sa. 12. Dez. 2020 um 10:33:
