### ISSUE TITLE
No function

### ISSUE THREAD

**Issue by craftyham** [bigtreetech/BTT-TFT35-E3-V3.0#54]
The Screen loads & I can flash Firmware to the screen. Unfortunately, nothing works, no touch, no encoder, & resetting the touch (reset.txt) loads but doesn't allow to click on red star.

**Comment by oldman4U** [comment]
Cut a USB cable and connect the red and black wire to 5V and GND after removing ALL other cables from TFT. Does it work then?

**Comment by craftyham** [comment]
> 
> 
> Cut a USB cable and connect the red and black wire to 5V and GND after removing ALL other cables from TFT. Does it work then?

I figured it out @oldman4U, The top two screws just needed backed off a smudge. Everything is as it should be now.

**Comment by oldman4U** [comment]
Perfect 

Happy printing
