### ISSUE TITLE
"no printer attached" error on skr e3 turbo

### ISSUE THREAD

**Issue by DannyGi82** [bigtreetech/BTT-TFT35-E3-V3.0#56]
I've installed today the skr e3 turbo on my ender 3 v2. The pack from amazon is comprensive with tft35-E3 v3.
I've follow the pin diagram and connect the tft cable to the board, update the firmware with last pre compiled, set the baudrate for both to 115200, but the error is still in place.
The port configuration is:
`#define SERIAL_PORT -1
#define SERIAL_PORT_2 0`

Uncommented the `#define CR10_STOCKDISPLAY` and `#define REPRAP_DISCOUNT_SMART_CONTROLLER` and `#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`

Marlin emulation work perfectly.

How i can fix this? Thank you

**Comment by oldman4U** [comment]
Only CR-10 Stockdisplay and serial port 2 and -1.

**Comment by DannyGi82** [comment]
> Only CR-10 Stockdisplay and serial port 2 and -1.

Done. Same error message

**Comment by oldman4U** [comment]
Broken hardware? Most likely the cable.

**Comment by radek8** [comment]
-1 is a USB port
2 is TFT

set
 #define SERIAL_PORT 2
 #define SERIAL_PORT_2 - 1

**Comment by DannyGi82** [comment]
> Broken hardware? Most likely the cable.

No, the tft cable have rx and tx pin inverted.
Push out this pins from block and put in in right position and voilà the tft35 magically work!

**Comment by oldman4U** [comment]
So you mean that two of the five strings of the RS232 cable have been twisted and this cable came with the TFT?

**Comment by DannyGi82** [comment]
> So you mean that two of the five strings of the RS232 cable have been twisted and this cable came with the TFT?

Yes, exactly
