### ISSUE TITLE
Thermal runaway protection when using touch screen mode?

### ISSUE THREAD

**Issue by markbwalker** [bigtreetech/BTT-TFT35-E3-V3.0#58]
Can't seem to determine if the touch screen mode has an option to enable thermal runaway protection.  I think I've exhausted all the menus looking for it with no luck, and I don't see it in the config file either.  Apologies if somehow I missed it.

I could use the Marlin mode since I know it's there, but I have a hitch.  The SD microcard on the SKR Mini E3 V2 failed, so I use the slots on the TFT35 instead.

While I'm at it, sort of a related question: When in touch screen mode, what version of Marlin is actually being used?  i.e. Does the TFT have it's own Marlin version separate from the motherboard?

Running the latest BTT TFT35 files as of 1/18/2021.

**Comment by oldman4U** [comment]
Hi. I would recommend to close this ticket here and ask the same questions in the firmware repository.

**Comment by markbwalker** [comment]
> Hi. I would recommend to close this ticket here and ask the same questions in the firmware repository.

Thanks - makes sense.

**Comment by markbwalker** [comment]
Moved to TFT firmware section.
