### ISSUE TITLE
Pinot diagram needs work

### ISSUE THREAD

**Issue by xeddog** [bigtreetech/BTT-TFT35-E3-V3.0#59]
The pinout diagram appears to have all of the pins, but the display image in the front and not the back where the pins are.  Are the pins backwards, or just the image?

**Comment by radek8** [comment]
Yes, it is illogical.
The image is from the front of the display, not the connectors.
The description corresponds to the picture.

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/105578957-07089000-5d84-11eb-9b84-053f8d9be1d7.png)

**Comment by tkhub** [comment]
![issue](https://user-images.githubusercontent.com/24850071/145759423-b5c4a959-d08a-48e1-988b-9a409d921052.jpg)
I have confirmed pin assign by circuit tester.
The manual explains top (flont) view.
(NOT BUTTOM VIEW)
