### ISSUE TITLE
Encoder Wheel LED_ORANGE defined wrong

### ISSUE THREAD

**Issue by critter42** [bigtreetech/BTT-TFT35-E3-V3.0#6]
when you select "Orange" for the Encoder Wheel LED, it is actually Green.

Looking in src\User\Menu\ledcolor.h  you have:

#define LED_ORANGE                0x00FF8C00

Since  you are defining the color in GRB order rather than RGB order, it should read

#define LED_ORANGE                0x008CFF00

However I find that 

#define LED_ORANGE                0x0045FF00

Is much closer with these LEDs to what I think of as orange. 0x008CFF00 is still way too heavy on the green - the green portion of these LEDs really overpowers the other colors.

**Comment by thisiskeithb** [comment]
Thanks for the report!

I've put in a PR to fix both Orange & Violet LED colors, so be sure to grab firmware from the main TFT firmware repo once this is merged: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/527

>  the green portion of these LEDs really overpowers the other colors.

I agree. Even pure white (`0x00FFFFFF`) has a green tinge to it.

**Comment by oldman4U** [comment]
Hello critter42.

Have you tried the latest Master Branch which should solve the issue you have reported.

Please let us know

Thank you

**Comment by critter42** [comment]
No, as I had already fixed it in my code.
Danny

**Comment by thisiskeithb** [comment]
Please close the issue if your problem is resolved.
