### ISSUE TITLE
Where are the Schematics

### ISSUE THREAD

**Issue by Duality4Y** [bigtreetech/BTT-TFT35-E3-V3.0#62]
Are there any schematics available for this device?

**Comment by radek8** [comment]
only pin connection here
https://github.com/bigtreetech/BTT-TFT35-E3-V3.0/tree/master/Hardware

**Comment by Duality4Y** [comment]
I was looking for the Actuall schematics though :) but thanks. I allready lost motivation anyway :P

**Comment by jerryhprado** [comment]
This is why I stopped using Bigtree stuff. I must have schematics for my electronics.
