### ISSUE TITLE
Encoder bug

### ISSUE THREAD

**Issue by craftyham** [bigtreetech/BTT-TFT35-E3-V3.0#69]
I have a E3 mini 1.2 & TFT35 E3 V3, running latest version of Marlin bugfix. I've noticed the encoder can control the selected or last moved axis in motion(move) on the touch screen screen mode, when i returned to the main screen the speed percent was increased. The encoder also increases the speed percentage while on the main screen in touch mode like it should if in Marlin mode.

**Comment by radek8** [comment]
This is a known issue.
It was solved using cables EXP1 and EXP2.
The problem persists when using the EXP3 cable.
This is your case.

Many tickets have already been opened on this topic.
for example.
https://github.com/bigtreetech/BTT-TFT35-E3-V3.0/issues/57

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by craftyham** [comment]
> 
> 
> This is a known issue.
> It was solved using cables EXP1 and EXP2.
> The problem persists when using the EXP3 cable.
> This is your case.
> 
> Many tickets have already been opened on this topic.
> for example.
> #57

Thank you for catching me up on the issue. I'll look into in further using the ^57link^

**Comment by fiveorders** [comment]
I didn't want to open up another thread for the same issue, I am using TFT70 and EXP1 and EXP2 cables connected with the Serial cable. Speed changes with the encoder knob when adjusting other things. I have flashed the nightly build Marlin which has been recommended on the other thread. 

Any news about this? If it is not fixed, is it possible to disable the speed alteration feature by the knob? Or is it possible to completely disable the knob on Touch Screen Mode?

**Comment by oldman4U** [comment]
You can not use the knob in touchscreen mode.

Using EXP1 and 2 with v27 of the touchscreen firmware this issue should be fixed.

Using EXP3 this issue can not be fixed because the hardware does not allow this.

**Comment by fiveorders** [comment]
I downloaded v27 going to try in an hour after the print job. Is the knob completely being disabled on this new firmware? You need the knob button to switch between modes... Thank you

**Comment by oldman4U** [comment]
The button should work normally in touchscreen and Marlin mode but does not change speed when used in touchscreen mode. But again, this only works in case your TFT is connected to the mainboard using EXP1 AND 2.

**Comment by fiveorders** [comment]
Yes I connected EXP1 EXP2 and the Serial for Touchscreen Mode. Many thank you again.

**Comment by radek8** [comment]
As oldman4U writes
- the condition is the current FW in TFT
- connection of cables EXP1 and EXP2
- current Marlin (nightly build)

Marlin (nightly build) provides a write in the pin definition file for your board that deactivates the encoder in touch mode for Marlin.
You didn't say what kind of board you have with Marlin, so I can't say that your board has the necessary adjustment in the definition of pins.

PS:
You do not only need to switch the encoder to switch modes, but also hold your finger on the display :-)

**Comment by fiveorders** [comment]
I use the FLYF407ZG. I have successfully installed the v27. Will check this soon. Many thanks, guys.

**Comment by radek8** [comment]
Your board has not defined the necessary modification.
Add the following line to the pins_FLYF407ZG.h file

  #if ENABLED (REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER)
  #define BTN_ENC_EN        PE7 // Detect the presence of the encoder
  #endif


Sorry for the mistake, corrected

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/115141728-3440a380-a03e-11eb-945a-d6cf7c0a04da.png)

**Comment by radek8** [comment]
In Marlin you only need to activate 1 display driver:
And this:

#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

**Comment by fiveorders** [comment]
Will do! Thanks, one question, will the SD card be available both in touch and text mode?

**Comment by radek8** [comment]
It depends on the parameter setting in Marlin
#define SDCARD_CONNECTION

When setting up (I prefer)
#define SDCARD_CONNECTION ONBOARD
Only an onboard SD card will be available in Marlin.
Both Onboard and TFT SD cards will be available in touch mode.

#define SDCARD_CONNECTION LCD
In both Marlin and touch mode, only the SD card on the TFT will be available.

USB flash drive is always available only in touch mode

**Comment by fiveorders** [comment]
I have defined #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

but cannot find pins_FLYF407ZG.h on my Marlin repo? Should I download it from somewhere

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/115156193-5dcfee00-a083-11eb-822a-37275e448336.png)

**Comment by fiveorders** [comment]
Awesome, thank you, now flashing and trying

**Comment by fiveorders** [comment]
#define SDCARD_CONNECTION LCD
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

I defined these and got error as below, does not compile

Marlin/src/HAL/STM32/../../inc/SanityCheck.h:2405:4: error: #error "Please select only one LCD controller option."

**Comment by radek8** [comment]
And what do you not understand about that mistake? :-)
Comment out the other LCD drivers

**Comment by fiveorders** [comment]
//#define REPRAP_DISCOUNT_SMART_CONTROLLER    yes this one:) brain freeze sorry:)

**Comment by fiveorders** [comment]
> Your board has not defined the necessary modification.
> Add the following line to the pins_FLYF407ZG.h file
> 
> #if ENABLED (REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER)
> #define BTN_ENC_EN PE7 // Detect the presence of the encoder
> #endif
> 
> Sorry for the mistake, corrected

I added the text below to pins_FLYF407ZG.h because I am using 2004 mode. Still, the speed being altered when I am changing Nozzle temp i.e. 

#if ENABLED (REPRAP_DISCOUNT_SMART_CONTROLLER)
#define BTN_ENC_EN PE7 // Detect the presence of the encoder
#endif

EXP1 and EXP2 and TFT Serial cables are connected. Marlin Nightly build installed.

Any ideas? Thanks

**Comment by radek8** [comment]
I provided the ideas, you didn't follow them ...

**Comment by radek8** [comment]
Add the following line to the pins_FLYF407ZG.h file
#if ENABLED (REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER)
#define BTN_ENC_EN PE7 // Detect the presence of the encoder
#endif

In Marlin you only need to activate 1 display driver:
And this:
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

set in the config.ini file:
marlin_type:0

**Comment by fiveorders** [comment]
So this fix won't work with 2004 LCD mode? It needs to be 12864 mode. Am I correct?

**Comment by radek8** [comment]
yes

**Comment by radek8** [comment]
Display 2004 - HD47780
uses Pin D7 for communication and therefore cannot be used to turn off the encoder.

**Comment by fiveorders** [comment]
Probably you are questioning why would someone uses 2004 if there is 12864, there is an explanation for sure. Many thank you for your help. Please send your contact information to venedikli at gmail com and also if you have oldman4u contact information please send that as well. I will add you guys to a list for some perks...👍

**Comment by radek8** [comment]
I don't know what the benefits of LCD 2004 are.
If you insist on LCD 2004 and don't need a beeper.
Use the driver for LCD 2004 in Marlin. Deactivate sound in Marlin. Use the beeper control pin to turn off the encoder.

repair:
Sorry, it won't work. An adjustment would have to be made in the FW of the display ...

**Comment by radek8** [comment]
I would have one less comfortable solution, but it allows any display, including LCD 2004.
The speed only changes when Marlin is on the status screen and you turn the knob.
In Marlin, turn off automatic return to the status screen.
After turning on the printer in touch mode, click the knob once.
Marlin goes to the menu and stops responding to turning the knob.
Now you can turn the knob, but be careful, don't try to click :-)
You use the long touch on the display to switch the mode.

**Comment by fiveorders** [comment]
Okay many thanks, I will consider the previous option without sound. Or stay with the 12864

**Comment by oldman4U** [comment]
Or simply use the touchscreen in touchscreen mode and the encoder in Marlin
mode.

Or, replace the mainboard😁

Happy printing

fiveorders ***@***.***> schrieb am Mo. 19. Apr. 2021 um 08:48:

> Okay many thanks, I will consider the previous option without sound. Or
> stay with the 12864
>
>

**Comment by radek8** [comment]
@fiveorders 
Were you successful? Did you manage to deactivate the speed change by turning the knob in touch mode?

**Comment by fiveorders** [comment]
@radek8 yes many thank you. I moved to 12864 mode for this purpose. However I have a worser situation after upgrading to v27 on TFT70 and Marlin Nightly Build 2.0. I am having little blobs during the print due to very short pauses of the extrduer.... 

Searched for it and saw that I am not the only one. I think I sadly had to give up on TFT70 and move to 2004 or 12864

**Comment by fiveorders** [comment]
You guys didn't send us your contact information, did you? @radek8 @oldman4U

**Comment by radek8** [comment]
What contact information do you need?

**Comment by fiveorders** [comment]
> What contact information do you need?

your emails... 👍

**Comment by oldman4U** [comment]
We are available exclusively through this repository 🤓😜

**Comment by fiveorders** [comment]
Alright guys, not for private support, I just wanted to do some favours to you as you helped me a lot here... thanks anyway

**Comment by oldman4U** [comment]
You are very welcome. radek is the hero in this case. 👍🏻
