### ISSUE TITLE
Issue: Dialog Text not legible

### ISSUE THREAD

**Issue by LTSpenny** [bigtreetech/BTT-TFT35-E3-V3.0#72]
![IMG_9153](https://user-images.githubusercontent.com/86140833/122631653-04377000-d082-11eb-8a59-cef2297ca7f5.jpg)
 
I have a few screens and pop ups that have text that reads like the above picture. I used the standard configuration file and TFT35_V3.0_E3.27.x.bin 

any way to fix it? 

Along with this, I tried deleting a few of the "pre set" configurations for other materials I will most likely never use and that screen ended up looking like the above. Thank you for any assistance!

Printer im hooked up to is a Creality Ender Max with a SKR E3 Turbo board running Marlin Bug Fix 2.0.

**Comment by radek8** [comment]
The problem has already been fixed. Use the current FW

**Comment by LTSpenny** [comment]
Hi sorry im new to this. I thought e3.27.bin was the current. Do you mean just recompile from source? Thank you for taking the time to reply!

**Comment by LTSpenny** [comment]
Edit- sorry figured it out just re-downloaded latest files. Thanks for the help!
