### ISSUE TITLE
Y axis not homing in touch screen mode

### ISSUE THREAD

**Issue by Tktrouble** [bigtreetech/BTT-TFT35-E3-V3.0#77]
Hi  I have been having problems with my screen I hope someone can help because I have tried big tree tech and I sill got no where.

In marlin mode and on my computer it home all axis fine, but when I use the touch screen the y axis won’t home. I have tried it on 2 different tft35 e3 v3 screens and tried changing the cords. same out come. 
Thanks for the help

marlin firmware is: 2.0.9.3 
Board is: BTT SKR PRO 1.2
Tft 35 e3 v3 firmware is form: January 25

**Comment by Tktrouble** [comment]
Sorry not the best video of the problem 
https://user-images.githubusercontent.com/98793743/151911396-e0a20fe0-1e10-4a80-a23b-c52f3c6cc463.MOV
Thanks

**Comment by radek8** [comment]
Marlin writes the error message, not the display.
You have a problem with the Marlin configuration

**Comment by Tktrouble** [comment]
They why does it home when use marlin mode 
But doesn’t with the touch screen
If it is marlin what do you think I need to change in it

**Comment by radek8** [comment]
send configuration

**Comment by radek8** [comment]
What end stops do you use?

![image](https://user-images.githubusercontent.com/46979052/152063784-bccbd080-fefb-424f-9617-90cbe53149df.png)

**Comment by Tktrouble** [comment]
That happens when the Y Axis/ bed homing

**Comment by radek8** [comment]
I understand.
You send configuration files.

Do you use microswitches or without sensor guidance?

**Comment by radek8** [comment]
Did I hear a click on the X-axis, microswitches?

**Comment by radek8** [comment]
It is late I am going to sleep

**Comment by Tktrouble** [comment]
Ok 
Ya I am using end stop microswitches
I will send the files when I get home thanks

**Comment by Tktrouble** [comment]
here is my files
[Marlin-2.0.x skr pro1.2-tft35-bltuch.zip](https://github.com/bigtreetech/BTT-TFT35-E3-V3.0/files/7983354/Marlin-2.0.x.skr.pro1.2-tft35-bltuch.zip)

**Comment by Tktrouble** [comment]
here is my files
[Marlin-2.0.x ET5X.zip](https://github.com/bigtreetech/BTT-TFT35-E3-V3.0/files/7983365/Marlin-2.0.x.ET5X.zip)
thanks for the help

**Comment by radek8** [comment]
In Marlin you have set up
#define PREHEAT_BEFORE_LEVELING
Therefore, the Home function does not run unless the printer is preheated.
Isn't that your problem?
Try disabling this option

**Comment by Tktrouble** [comment]
It might be 
But would that affect just for when it’s just homing not doing bed leaving

**Comment by radek8** [comment]
I don't understand what you mean.
The error says: Homing Failed

**Comment by Tktrouble** [comment]
I tryed the some thing happened
So I tried marlin 2.0.9.2 and it works
Thanks for the help

**Comment by radek8** [comment]
Then there may be a problem in Marlin.
Close your ticket here
