### ISSUE TITLE
No printer attached

### ISSUE THREAD

**Issue by Akds4877** [bigtreetech/BTT-TFT35-E3-V3.0#81]
Hey, 

i just bought the TFT70 and Octopus Pro and i uploaded the Firmware in the Board(Marlin) and TFT (TFT70 GD ) and i have done all the troubleshooting with the bpard and the TFT but still there is a error "No Printer Attached" in the display and when i try to connect my board with the Pronterface, again it shows the error and does not connect with the PC.

So please Help me how should i get rid of this problem.

**Comment by radek8** [comment]
Send the Marlin and TFT configuration files.
Send photos connected to the serial cable.

**Comment by Akds4877** [comment]
Thanks for reply

I resolved this issue

thank you

**Comment by radek8** [comment]
Then close the ticket
