### ISSUE TITLE
Getting error when compiling

### ISSUE THREAD

**Issue by XeroZar** [bigtreetech/BTT-TFT35-E3-V3.0#84]
Hi guys, hope some knows a fix for this... When I compile the firmware, I get the following 2 errors...
==============================================================
TFT\src\User\Hal\STM32_USB_OTG_Driver\src\usb_core.c: In function 'USB_OTG_WritePacket':
TFT\src\User\Hal\STM32_USB_OTG_Driver\src\usb_core.c:178:7: warning: 'packed' attribute ignored for type 'uint32_t *' {aka 'long unsigned int *'} [-Wattributes]
  178 |       USB_OTG_WRITE_REG32( fifo, *((__packed uint32_t *)src) );
      |       ^~~~~~~~~~~~~~~~~~~
TFT\src\User\Hal\STM32_USB_OTG_Driver\src\usb_core.c: In function 'USB_OTG_ReadPacket':
TFT\src\User\Hal\STM32_USB_OTG_Driver\src\usb_core.c:204:5: warning: 'packed' attribute ignored for type 'uint32_t *' {aka 'long unsigned int *'} [-Wattributes]
  204 |     *(__packed uint32_t *)dest = USB_OTG_READ_REG32(fifo);
==============================================================

Anyone have a fix for this... I've been looking for a while found suggestions but no fixes.
(p.s. Sorry don't know why the above text is soo big)

**Comment by XeroZar** [comment]
Ok so ended up finding the problem, there was a syntax error  in usb_core file extra space after
'{' this bracket (rolling eyes).

But now getting different warnings...

Warning! `src_filter` configuration option in section [env:BIGTREE_TFT24_V1_1] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:BIGTREE_TFT35_V1_0] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:BIGTREE_TFT35_V3_0] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:BIGTREE_TFT70_V3_0] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:BIGTREE_GD_TFT24_V1_1] is deprecated and will be removed in the next release! Please use `build_src_filter` instead       
Warning! `src_filter` configuration option in section [env:BIGTREE_GD_TFT35_V3_0] is deprecated and will be removed in the next release! Please use `build_src_filter` instead       
Warning! `src_filter` configuration option in section [env:BIGTREE_GD_TFT70_V3_0] is deprecated and will be removed in the next release! Please use `build_src_filter` instead       
Warning! `src_filter` configuration option in section [env:MKS_TFT32_V1_3] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:MKS_TFT35_V1_0] is deprecated and will be removed in the next release! Please use `build_src_filter` instead

I've installed the latest pio dev build and all is up to date but still getting this issue.

**Comment by XeroZar** [comment]
Ok figured it out again. With no help. Please close this thread.

**Comment by radek8** [comment]
The ticket must be closed by the person who opened it, i.e. you
