### ISSUE TITLE
Permanent blank screen in Marlin Mode on SKR 1.3

### ISSUE THREAD

**Issue by Andy-ABTec** [bigtreetech/BTT-TFT35-E3-V3.0#9]
Hi,
Just purchased a BTT TTF35-E3 V3.0 to use on my Ender 3 along with an existing BTT SKR 1.3 board.

Touch Mode appears to be fine (I don't get the "No printer attached" message), but Marlin Mode just presents a blank screen. All firmware is the latest available, Marlin 2.03 for the SKR and BIGTREE_TFT35_V3.0.25.1 for the TFT. I'm using the Unified Menu Material theme, and the boards are interconnected with all three cables (correctly orientated on EXP1, EXP2 and RS232/TFT).

The SKR is using BTT2209 V1.2 driver boards for X,Y,Z and E0 in UART Mode.

Happy to provide any other information you need.

Also noticed that the  mode selection screen seems counterintuative, in that turning the knob clockwise (top to the right) moves the selection to the left and vice versa.

Thanks in advance for a timely response.

Andy B.

Having played around a little more it would seem that there is possibly something going on in Marlin Mode in that I can change the background colour of the screen using Menu>Settings>Screen in Touch Mode.

The Marlin Mode screen updates to the new colour, but no text is visible, its just a solid colour.

**Comment by hfog** [comment]
After you go to Marlin mode, try turning the knob. It often presents a blank screen until you turn the knob, causing the screen to refresh.

**Comment by Andy-ABTec** [comment]
Been there - done that - nothing...

**Comment by Andy-ABTec** [comment]
Having looked further this does not appear to be a firmware problem, I have now tried:
```
BIGTREE_TFT35_V3.0.25.1.bin
BIGTREE_TFT35_V3.0.25.bin
BIGTREE_TFT35_V3.0.24.2.bin
```
From the GitHub Repository and they all have the same problem - the screen is TOTALLY blank in Marlin Mode...

**Comment by testproggie** [comment]
After having struggled greatly (noobie here) I am at the same point although I have SKR 1.4 Turbo. Things work through the BTT menus, but on the Marlin side it is just a blank screen. I'm am not certain at this point whether I even need to use the Marlin side, but it would be nice to look through everything. Still working on getting other stuff right in the config files.

**Comment by Andy-ABTec** [comment]
So, I just built my own firmware for the screen...
I made a small change to Configuration.h, removing the comment mark from the Banner Text definition viz:

`   #define` ST7920_BANNER_TEXT "LCD12864 Simulator"

And now when I switch to Marlin Mode I see the banner but the rest of the screen is still blank and no amount of turning or pressing the encoder has any effect. So the actual screen appears to be functional but not displaying the Marlin menus...

**Comment by testproggie** [comment]
Wow, being a newbie in this stuff is tough. I still haven't found a good guide that explains all the functions of Marlin. Lots of youtube videos, but hunting through videos to see if they address your particular problem is time consuming. As to the issue above, my issue is that in the Marlin configuration.h file there is no LCD defined by default. For me uncommenting "//#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER" was the trick. Hopefully somebody will stumble across the and be able to make use of it  :)

**Comment by Andy-ABTec** [comment]
I know, found that a while ago, fixed the "No printer attached" message in Touch Mode...

**Comment by Andy-ABTec** [comment]
For what it's worth... **ITS WORKING!** - and I think its a Marlin issue...

So, as a last resort while I still have some hair I setup the SKR 1.3 and the TFT35-E3 V3.0 on the bench with four BTT TMC2209 V1.2's, interconnecting EXP1 to EXP1, EXP2 to EXP2 and TFT to RS232, and powered by the USB connection on  the SKR (with no messy cable twisting).

Firmware on the TFT is 25.1 with the Unified Menu Material theme.
Firmware on the SKR 1.3 is **bugfix-2.0x** commit 75e3aa1.

I ignored the "Ender 3" configuration and manually made the following changes:

platformio.ini
```
default_envs = LPC1768
```
Configuration.h
```
#define SERIAL_PORT -1
#define SERIAL_PORT_2 0
#define BAUDRATE 115200
#define MOTHERBOARD BOARD_BTT_SKR_V1_3
#define X_DRIVER_TYPE  TMC2209
#define Y_DRIVER_TYPE  TMC2209
#define Z_DRIVER_TYPE  TMC2209
#define E0_DRIVER_TYPE TMC2209
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
```
Powered up, switched to Marlin Mode (blank screen) and clicked again - and Voila!

This has **NEVER** happened before and its not for the want of trying...

While I've got everything on the bench I'll fiddle about a bit more and see if I can isolate the actual problem, but for now at least I'm a happy bunny!

**Comment by KennyD42** [comment]
I'm noticing you have set your

platformio.ini
default_envs = LPC176

Is that the proper designation for the SKR 1.3? Mine is set at LPC1768. Could this be my problem??

**Comment by KennyD42** [comment]
> For what it's worth... **ITS WORKING!** - and I think its a Marlin issue...
> 
> So, as a last resort while I still have some hair I setup the SKR 1.3 and the TFT35-E3 V3.0 on the bench with four BTT TMC2209 V1.2's, interconnecting EXP1 to EXP1, EXP2 to EXP2 and TFT to RS232, and powered by the USB connection on the SKR (with no messy cable twisting).
> 
> Firmware on the TFT is 25.1 with the Unified Menu Material theme.
> Firmware on the SKR 1.3 is **bugfix-2.0x** commit 75e3aa1.
> 
> I ignored the "Ender 3" configuration and manually made the following changes:
> 
> platformio.ini
> 
> ```
> default_envs = LPC176
> ```
> 
> Configuration.h
> 
> ```
> #define SERIAL_PORT -1
> #define SERIAL_PORT_2 0
> #define BAUDRATE 115200
> #define MOTHERBOARD BOARD_BTT_SKR_V1_3
> #define X_DRIVER_TYPE  TMC2209
> #define Y_DRIVER_TYPE  TMC2209
> #define Z_DRIVER_TYPE  TMC2209
> #define E0_DRIVER_TYPE TMC2209
> #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
> ```
> 
> Powered up, switched to Marlin Mode (blank screen) and clicked again - and Voila!
> 
> This has **NEVER** happened before and its not for the want of trying...
> 
> While I've got everything on the bench I'll fiddle about a bit more and see if I can isolate the actual problem, but for now at least I'm a happy bunny!

I noticed your default_envs = LPC176 for the SKR 1.3. Mine is set to LPC1768. Could this be my problem?

**Comment by Andy-ABTec** [comment]
Absolutely not - it's my bad copy-pasting!

**Comment by KennyD42** [comment]
I've tried to solution that you've typed in and it does not work

**Comment by steinboy** [comment]
I had the same issue with "#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER"  uncommented but then I commented out #define CR10_STOCKDISPLAY and then it worked!

After first switching to the Marlin view though the screen is black until you move the knob.

**Comment by Andy-ABTec** [comment]
my "#define CR10_STOCKDISPLAY" was already commented out but Marlin bugfix-2.0x seemed to resolve the problem (https://github.com/bigtreetech/BTT-TFT35-E3-V3.0/issues/9#issuecomment-586908632), however I never managed to get to the bottom of the problem...
The knob twist thing is normal, but mine wouldn't display at all even thought I could get the Simulator message to display in Marlin mode.

**Comment by ijwoo1** [comment]
Thank you!

This had me scratching my head. 

I found Baudrate of 250000 seems to sync faster than 115200, so the key changes I had to make in configuration.h for an Ender 5 with SKR 1.3 were:

//#define CR10_STOCKDISPLAY
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
#define BAUDRATE 250000

Points to note: you will get "No printer attached" for about 30s after switching on the printer. You may need to go to Graphic mode, menu, settings and correctly set the baudrate but from then on it should connect after a small delay, without needing to change anything.

When you switch to Marlin mode, by pushing in the encoder for 3s, you will have a blank screen until you refresh the display by rotating the encoder.

**Comment by dmurray01** [comment]
hardware; 
1. only use one cable which you connect to exp1 on board and exp 3 on display
2. connect tft cable to board other than reset pin, connect other side to display normally

software;
1. uncomment #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

**Comment by merinkumar** [comment]
I too had this issue today. But now am able to connect the TFT35V3 in both ways 2 EXP cables and 1 EXp cables. In both case the TFT black cable was connected to my SKR 1.3 board.

One EXP cable:
#define CR10_STOCKDISPLAY
//#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
#define BAUDRATE 250000
connect EXP3 on TFT35V3 to EXP1 on SKE1.3 board
connect black TFT cable (Note : dont connect the REST PIN to SKR1.3)

Two EXP cable:
//#define CR10_STOCKDISPLAY
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
#define BAUDRATE 250000
EXP1 on SKR to EXP1 on TFT35
EXP2 on SKR to EXP2 on TFT35
TFT black cable connected as usual.

if it helps any one.

thanks

**Comment by NiiXXiiN** [comment]
> I too had this issue today. But now am able to connect the TFT35V3 in both ways 2 EXP cables and 1 EXp cables. In both case the TFT black cable was connected to my SKR 1.3 board.
> 
> One EXP cable:
> #define CR10_STOCKDISPLAY
> //#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
> #define BAUDRATE 250000
> connect EXP3 on TFT35V3 to EXP1 on SKE1.3 board
> connect black TFT cable (Note : dont connect the REST PIN to SKR1.3)
> 
> Two EXP cable:
> //#define CR10_STOCKDISPLAY
> #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
> #define BAUDRATE 250000
> EXP1 on SKR to EXP1 on TFT35
> EXP2 on SKR to EXP2 on TFT35
> TFT black cable connected as usual.
> 
> if it helps any one.
> 
> thanks

I just made an account to say thank you, it was that reset pin that made all the difference!

**Comment by bryanhunwardsen** [comment]
I just want to add an alternate solution for anyone facing this issue where the listed solution was not the issue.

When switching to emulation mode the screen does not load:
A simple issue I faced and resolved, the Marlin Configuration.h did not match the TFT35 config.ini for the screen type.
Marlin was set to LCD12864(#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER), and I had overridden the TFT35 to LCD2004. Flashing either/both to unify to the same screen type corrected the issue.

In my case I re-flashed the TFT to LCD12864 as no recompile required and LCD12864 is a better utilization of the TFT35 screen real-estate.

**Comment by ZoserLock** [comment]
> I too had this issue today. But now am able to connect the TFT35V3 in both ways 2 EXP cables and 1 EXp cables. In both case the TFT black cable was connected to my SKR 1.3 board.
> 
> One EXP cable: #define CR10_STOCKDISPLAY //#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER #define BAUDRATE 250000 connect EXP3 on TFT35V3 to EXP1 on SKE1.3 board connect black TFT cable (Note : dont connect the REST PIN to SKR1.3)
> 
> Two EXP cable: //#define CR10_STOCKDISPLAY #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER #define BAUDRATE 250000 EXP1 on SKR to EXP1 on TFT35 EXP2 on SKR to EXP2 on TFT35 TFT black cable connected as usual.
> 
> if it helps any one.
> 
> thanks

Thanks you! changing the baudrate make it work for me
